package com.javaThree.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class PfmsUsageOne {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.TYPE
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.NAME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.AMOUNT
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.CHILDREN
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private Integer children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.CREATER_ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private Integer createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.CREATE_TIME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_usage1.DESCRIPT
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String descript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.ID
     *
     * @return the value of pfmsdb_usage1.ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.ID
     *
     * @param id the value for pfmsdb_usage1.ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.TYPE
     *
     * @return the value of pfmsdb_usage1.TYPE
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.TYPE
     *
     * @param type the value for pfmsdb_usage1.TYPE
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.NAME
     *
     * @return the value of pfmsdb_usage1.NAME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.NAME
     *
     * @param name the value for pfmsdb_usage1.NAME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.AMOUNT
     *
     * @return the value of pfmsdb_usage1.AMOUNT
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.AMOUNT
     *
     * @param amount the value for pfmsdb_usage1.AMOUNT
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.CHILDREN
     *
     * @return the value of pfmsdb_usage1.CHILDREN
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public Integer getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.CHILDREN
     *
     * @param children the value for pfmsdb_usage1.CHILDREN
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setChildren(Integer children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.CREATER_ID
     *
     * @return the value of pfmsdb_usage1.CREATER_ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public Integer getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.CREATER_ID
     *
     * @param createrId the value for pfmsdb_usage1.CREATER_ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setCreaterId(Integer createrId) {
        this.createrId = createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.CREATE_TIME
     *
     * @return the value of pfmsdb_usage1.CREATE_TIME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.CREATE_TIME
     *
     * @param createTime the value for pfmsdb_usage1.CREATE_TIME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_usage1.DESCRIPT
     *
     * @return the value of pfmsdb_usage1.DESCRIPT
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_usage1.DESCRIPT
     *
     * @param descript the value for pfmsdb_usage1.DESCRIPT
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }
}