package com.javaThree.mybatis.model;

public class PfmsSys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_sys.SYS_ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_sys.SYS_NAME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_sys.SYS_VALUE
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String sysValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pfmsdb_sys.SYS_DESC
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    private String sysDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_sys.SYS_ID
     *
     * @return the value of pfmsdb_sys.SYS_ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_sys.SYS_ID
     *
     * @param sysId the value for pfmsdb_sys.SYS_ID
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_sys.SYS_NAME
     *
     * @return the value of pfmsdb_sys.SYS_NAME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_sys.SYS_NAME
     *
     * @param sysName the value for pfmsdb_sys.SYS_NAME
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_sys.SYS_VALUE
     *
     * @return the value of pfmsdb_sys.SYS_VALUE
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getSysValue() {
        return sysValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_sys.SYS_VALUE
     *
     * @param sysValue the value for pfmsdb_sys.SYS_VALUE
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setSysValue(String sysValue) {
        this.sysValue = sysValue == null ? null : sysValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pfmsdb_sys.SYS_DESC
     *
     * @return the value of pfmsdb_sys.SYS_DESC
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public String getSysDesc() {
        return sysDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pfmsdb_sys.SYS_DESC
     *
     * @param sysDesc the value for pfmsdb_sys.SYS_DESC
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc == null ? null : sysDesc.trim();
    }
}