package com.javaThree.mybatis.dao;

import com.javaThree.mybatis.model.PfmsForm;
import com.javaThree.mybatis.model.PfmsFormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int countByExample(PfmsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int deleteByExample(PfmsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int insert(PfmsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int insertSelective(PfmsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    List<PfmsForm> selectByExample(PfmsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    PfmsForm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") PfmsForm record, @Param("example") PfmsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByExample(@Param("record") PfmsForm record, @Param("example") PfmsFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByPrimaryKeySelective(PfmsForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_form
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByPrimaryKey(PfmsForm record);
}