package com.javaThree.mybatis.dao;

import com.javaThree.mybatis.model.PfmsSys;
import com.javaThree.mybatis.model.PfmsSysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PfmsSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int countByExample(PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int deleteByExample(PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int deleteByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int insert(PfmsSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int insertSelective(PfmsSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    List<PfmsSys> selectByExample(PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    PfmsSys selectByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByExampleSelective(@Param("record") PfmsSys record, @Param("example") PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByExample(@Param("record") PfmsSys record, @Param("example") PfmsSysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByPrimaryKeySelective(PfmsSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pfmsdb_sys
     *
     * @mbggenerated Thu Apr 23 22:21:56 CST 2015
     */
    int updateByPrimaryKey(PfmsSys record);
}